### ISSUE TITLE
NAS-1 UML-Modell in Implementierungsschema konvertieren (ShapeChange)

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#10]
Das Datenbankschema, in das derzeit mit ogr2ogr NAS Dateien eingelesen werden, umfasst nicht das vollständige Anwendungsschema des AAA-Modells. Wenn also derzeit mit dem Werkzeug ogr2ogr NAS Dateien eingelesen werden, kann es passieren, dass Daten der GML-Dateien nicht in der Datenbank ankommen, weil die dazugehörigen Tabellen oder Attribute fehlen.
Des Weiteren verwendet ogr2ogr einen Mechanismus zur Abbildung von verschachtelten Objektstrukturen, der dazu führen kann, dass Daten in falsche gleichlautende Attribute geschrieben werden. In den Issues NAS wird beschrieben wie die genannten Unzulänglichkeiten behoben werden.
In NAS-1 ist keine Softwareentwicklung an diesem Repository durchzuführen, aber ein Ausgangsdatensatz für die weiteren Arbeiten zu erzeugen.
Laut GeoInfoDok 6.0.1, Abschnitt 4.2 Normen und Standards, muss das konzeptionelle UML-Modell des AAA-Anwendungsschemas in ein Implementierungsschema konvertiert werden um ein Modell zu erhalten, welches zur NAS Schnittstelle passt.
Die Erzeugung des Implementierungsschemas erfolgt mit dem Plug-In ShapeChange und der dazugehörigen Konfigurationsdatei mit den Konvertierungsregeln für das AAA-Modell. Der Export erfolgt aus Enterprise Architekt heraus in eine Metadata Interchange Datei (XMI) in der Version 1.0.

**Comment by chseip** [comment]
im Grunde wie [hier](http://www.adv-online.de/AAA-Modell/Dokumente-der-GeoInfoDok/GeoInfoDok-6-0/binarywriterservlet?imgUid=75b20eba-659a-c041-f840-1034072e13d6&uBasVariant=11111111-1111-1111-1111-111111111111) vorgeschlagen vorgegangen
- SSJavaCom.dll ins Windows-Verzeichnis verschoben
- nas.bat und Konfigurationen/NAS-6.0.1.xml angepasst
- nas.bat gestartet

Die geänderte eap Datei habe ich dann in EA geöffnet und die Modellstruktur sieht schon ganz anders aus. Da das oberste Paket aber "AFIS-ALKIS-ATKIS Anwendungsschema" heißt, habe ich mich am Beispiel auf Seite 80 der GeoInfoDok 6.0.1 orientiert und gesehen, dass AX_Leitung tatsächlich so aussieht, wie es im Implementationsschema aussehen soll.

P.S.: Habe die neuste Version der Tools genommen, also [1.02](http://shapechange.net/resources/dist/de/interactive_instruments/ShapeChange/AAATools/1.0.2/AAATools-1.0.2.zip), diese enthält ja auch die 6.0.1er Version des Modells

**Comment by pkorduan** [comment]
Hallo Christian,

der Link oben nach im Grunde wie geht nicht und sag mal welche Version von EA hast Du verwendet um dann die geänderte eap Datei zu öffnen und die xmi zu exportieren?

**Comment by jef-n** [comment]
Das `GeoInfoDok-6-0` ist über.  Vermutlich richtiger [Link](http://www.adv-online.de/AAA-Modell/Dokumente-der-GeoInfoDok/binarywriterservlet?imgUid=75b20eba-659a-c041-f840-1034072e13d6&uBasVariant=11111111-1111-1111-1111-111111111111).

**Comment by chseip** [comment]
Also bei mir hier geht der Link nach wie vor?!

**Comment by pkorduan** [comment]
Welche EA Version hattest Du verwendet, EA Desktop,
Professional, Corporate oder gar Ultimate?
Lege bitte auch die eap mit dem Implementierungsmodell in das Repository.

**Comment by pkorduan** [comment]
Im xmi2db_cseip sind noch Änderungen im sql Verzeichnis. Aktueller Branch Fix-1. Kannst Du das bitte mal committten und pushen. Dann ist das Issue dann auch durch.

**Comment by chseip** [comment]
EA Corporate Version 12.1.1227
Das sollte aber wie gesagt kaum ne Role spielen, die Doku sagt glaub ich als Mindestanforderung EA 8 oder 9...

**Comment by chseip** [comment]
Damit ich die eap des Implementierungsmodells in das Repository (=owncloud) legen kann, musst du mir erstmal eine Freigabe einrichten.

**Comment by pkorduan** [comment]
Am 29.04.16 um 17:12 schrieb chseip:

> Damit ich die eap des Implementierungsmodells in das Repository
> (=owncloud) legen kann, musst du mir erstmal eine Freigabe einrichten.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pkorduan/xmi2db/issues/10#issuecomment-215748642
> 
> Hab Dir eine Freigabe
> 5. Ergebnisse
> zugeordnet.

Gruß Peter

## 

GDI-Service Rostock
Dr. Peter Korduan
Joachim-Jungius-Str. 9
18059 Rostock
Tel: 0381 40344444
Mobil: 0175 5446411
E-Mail: peter.korduan@gdi-service.de
