### ISSUE TITLE
NAS-2 UML-Modell in Datenbank einlesen (xmi2db)

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#11]
Die im Schritt NAS-1 erzeugte XMI-Datei repräsentiert das Implementierungsschema als UML-Model in From von XML.
Es wird das Skript xmi2db weiterentwickelt, mit dem die UML-Dinge (Klassen, Generalisierungen, Typen, Assoziationen etc.) in eine PostgreSQL Datenbank geschrieben werden. Im Ergebnis gibt es die befüllten Tabellen für UML-Klassen, UML-Attribute, Klassengeneralisierungen, Beziehungen, Stereotypen und Datentypen. Die Inhalte dieser Datenbank bilden das gesamte ALKIS Schema als Meta-Schema ab.
Das Ergebnis ist
1. das angepasste Skript xmi2db und
2. ein Datenbankschema alkis_uml gefüllt mit den entsprechenden Modellelementen.

**Comment by chseip** [comment]
Einlesen funktioniert zunächst zwar ohne Fehlermeldungen, aber es wird nur ein kleiner Teil in die DB eingelesen, da
- [x] bei Klassen nicht tief genug itteriert wird

Funktioniert nun, alles was Paketmäßig gespeichert wird, in Funktion iteratePackage() ausgelagert. Sieht man auch sehr gut, wenn man im View "aaa_uml2.classes_attributes_types_gen" sich "AX_Leitung" und dessen Attribute anguckt, alles so, wie es sein soll.

weitere TODOs im Zusammenhang des Einlesens
- [ ] full_model View muss noch auf die tieferen Ebenen angepasst werden

**Comment by chseip** [comment]
full_model View im Moment nicht wichtig, deshalb close.
