### ISSUE TITLE
NAS-3 UML-Schema in Klassenschema überführen (db2classes)

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#12]
In diesem Schritt werden aus dem Meta-Schema für jede Klasse eine eigene Tabelle erstellt, die alle eigenen sowie abgeleitete Attribute beinhaltet. Des Weiteren beinhaltet dieses Datenbankmodell sämtliche Beziehungen zwischen den Klassen. An Hand dieses Modells können die Strukturen, wie sie in den GML-Dateien vorkommen abgefragt werden.
Das Ergebnis ist
1. das angepasste Skript db2classes und
2. ein Datenbankschema alkis_gml mit allen Klassen und Beziehungen die es in ALKIS gibt.

**Comment by chseip** [comment]
Ich hab da mal angefangen, reinzugucken
1. bei AAA heißt es "featureType" während es bei XPlan "FeatureType" heißt (Lösung LIKE '%eatureType')
2. Bei AAA wird nur eine Klasse mit Stereotype "featureType", die "general_id" = "-1" hat, zurückgegeben. Aber eigentlich muss es doch noch mehr Top Klassen geben?! (Lösung ausstehend...)

**Comment by chseip** [comment]
- [x] Geometrietypen richtig angeben (für XPlan bisher nur über Stereotype "Union"
- [x] Länge der Tabellen- und Pkey-Identifier auf max. 63 Zeichen beschränken
- [x] Kleinere Fixes (Query failed: ERROR: invalid byte sequence for encoding "UTF8", Anpassungen Groß-Kleinschreibung AAA<->XPlan)
- [x] Klassen mit Assoziationen auf sich selbst abbilden
- [x] Klassen mit mehrfachen Assoziationen auf sich selbst abbilden (es werden mehrfach gleichnamige Tabellen angelegt, aa_reo2aa_reo 2 mal)
- [x] Assoziationen vernünftig abbilden (navigable, 1:1, 1:n usw.) - Peter?
- [x] Komplexe Datentypen werden nicht (oder nicht vollständig?) übernommen. Bsp.: ax_flurstueck, Attribut "gemeindezugehoerigkeit" ist vom Typ AX_Gemeindekennzeichen, das wird nirgends hinterlegt. - Ich

**Comment by chseip** [comment]
Von meiner Seite aus fertig. Wirft keine Fehler mehr beim Import in die DB. Soeben commited (https://github.com/pkorduan/xmi2db/commit/b52ab510ca84d89a3c0ddbde2ad884b9e6dbedc8).

**Comment by chseip** [comment]
Hm, ich hab bemerkt, das einige Klassen fehlen, u.a.:
- "AA_Bestandsdatenauszug"
- "AD_GitterCoverage"
- "AD_PunktCoverage" (Attribut "lebenszeitintervall" vom DataType AA_Lebenszeitintervall)
- AX_BereichZeitlich (Attribut "intervall" vom Typ TM_Duration)
- "AA_Auftrag"
- "AX_Gemeindekennzeichen" (Attribut "Gemeindezugehörigkeit" der Klasse AX_Flurstueck verweist z.B. darauf)

Ich guck mal rein, was da los ist und warum die fehlen.

Es ist an sich rstma kein Wunder, denn die "uml_classes" Tabelle hat 698 Klassen und deshalb müsste es ja auch für jede Klasse dort eine entsprechende GML Klasse geben, oder nicht?
Ok, ich stell grad fest, nein, muss es nicht, die fehlenden Klassen sind alles DataTypes. Stellt sich nur die Frage, ob man DataTypes dan nicht auch gesondert ablegen müsste?

**Comment by pkorduan** [comment]
Ist soweit erledigt. Das Ergebnis kann unter http://gdi-service.de/xmi2db/db2classes.php abgefragt werden.
