### ISSUE TITLE
NAS-4 Erstellung des Datenmodells für den ogr Import (classes2ogr)

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#13]
Da die OGR-Bibliothek nur ein flaches Datenschema unterstützt, müssen nun für alle FeatureTypen die verschachtelten Typen (Complex Type) analysiert werden und deren Attribute als zusätzliche Attribute in die Tabelle der FeatureTypen übernommen werden. Dabei ist zu prüfen ob es Doppelungen bei der Benennung der Attribute geben kann. Die Vergabe von neuen Namen für Attribute, die mehrfach vorkommen wird mit dem Auftraggeber abgestimmt.
Es wird ein Skript erstellt, welches die Fälle ermittelt in denen gleichlautende Attribute vorkommen.
Dann wird mit dem Auftraggeber abgestimmt wie die umzubenennenden Attribute in den verschachtelten Elementen  heißen sollen.
Schließlich wird ein Skript erstellt mit dem das Datenschema geschrieben wird, in das später die ALKIS-Daten durch OGR importiert werden. Dieses Skript wird so erstellt, dass die Tabellen und Attribute, die im OGR-Schema angelegt werden durch eine Konfigurationsdatei ausgewählt werden können. In die Konfigurationsdatei können alle Klassen und deren Attribute angegeben werden, die nicht das OGR-Schema übernommen werden sollen. Dadurch lassen sich bundeslandspezifische Profile erstellen.
Der Auftraggeber erstellt eine Konfigurationsdatei für Mecklenburg-Vorpommern und eine für Rheinland-Pfalz. In die Konfigurationsdatei werden die Klassen und Attribute aufgenommen, die derzeit auch nicht im ALKIS Schema für den OGR Import vorhanden sind. Die vollständige und richtige Befüllung des Konfigurationsskriptes an Hand des Objektartenkataloges des Landes obliegt dem Auftraggeber, bzw. Nutzer des Skriptes.
Das Ergebnis ist
- [x] 1. das Skript classes2ogr,
- [x] 2. eine Umbenennungsliste von gleichlautenden Attributnamen,
- [x] 3. eine Konfigurationsdatei zum Ausschließen von Klassen und Attributen
- [x] 4. ein Datenbankschema alkis zum Einlesen von NAS-Dateien mit ogr2ogr
  Damit das Einlesen in dieses alkis Schema funktioniert ist aber noch NAS-5 notwendig!

**Comment by chseip** [comment]
Für mich erstmal mit ba445654b1cd4100007f61d05b6bdf550d928c29 erledigt. Genauer wusste ich es nicht.

Geht die GML Klassen durch (z.B. `aaa_gml_classes`) und prüft, ob sie auch im UML Modell vorkommen (z.B. `aaa_uml`). Wenn ja, werden die komplexen Attribute in ein flaches Schema gebracht: es wird geprüft, ob Attribut von einem komplexen Datentyp ist und wenn ja, werden desen Attribute geladen. Das Originalattribut wird in der Tabelle gelöscht und die neuen Attribute hinzugefügt (Benennung analog PostNAS, zu lange Namen werden abgeschnitten, dopplungen werden durch Zahl am Ende + Kommentar begegnet). Ich hab es auch schon mal durchlaufen lassen. Ergebnis sieht man im Schema `aaa_gml_classes_test`.

Die Ausgabe des Skriptes sieht wie folgt aus:
1. SQL Skript
2. Doku Ersetzungen von komplexen Datentypen in flaches Schema
3. Doku Ersetzungen von gleichlautendenden Attributnamen

Das ganze nutzt auch die conf Datei `database_conf.php`. Dort können im Array `$classesOut[]` Klassen und in `$attributesOut[]` Attribute ausgeschlossen werden.

**Comment by pkorduan** [comment]
Die Konfigurationsdatei steht in conf und heißt filter_sample.json. Ich hab auch noch weitere für Bundesländer angelegt. Die werden dann nach Bedarf ergänzt. Welcher Filter verwendet werden soll muss in database_conf.php gesetzt werden. In der Default conf habe ich filter.json eingesetzt. Neu beginnende müssen sich also erstmal eine leere filter.json anlegen. Wenn die in der Konfigurationsdatei eingetragene Datei nicht gefunden wird, kommt ein Hinweis in die Logdatei und es wird nichts gefiltert.
