### ISSUE TITLE
NAS-5 Erstellung eines Umbenennungsskriptes (nas2ogrgml)

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#14]
OGR benennt Attribute von verschachtelten Klassen, die mehrfach vorkommen derart um, dass der Pfad des XML-Dokumentes vorangestellt wird. Das kann dazu führen, dass die Namen für die Attribute zu lang werden und bei der Verwendung zum Einlesen von Daten abgeschnitten werden. Aus diesem Grund werden die XML-Dateien vor dem Einlesen so umbenannt, dass die verschachtelten Typen keine Attribute mehr haben, die gleich lauten wie die vom FeatureType.
Des Weiteren ignoriert ogr2ogr Attribute wie „zeigtaufexternes“. Auch diese werden umbenannt werden können.
Die Umbenennung erfolgt nach den Vorgaben aus dem NAS-4 (Umbenennungsliste). Da die XML-Dateien dann vor dem Einlesen schon umbenannt sind und das Datenmodell, in das eingelesen wird, ebenfalls diese Namen verwendet, werden alle Daten, die der Endnutzer in seinem alkis Schema führen möchte korrekt eingelesen.
Das Ergebnis ist
1. das Umbenennungsskript nas2ogrgml

**Comment by chseip** [comment]
Erster Versuch mit Bash, siehe https://github.com/pkorduan/xmi2db/commit/7f05bab8fb73fd7601b9740b678f336326b0d6d4

Aufruf z.B. über
`./nas2ogrgml.sh ../Testdaten/aaa_gml/Bestandsdaten.xml testOut.gml mini`

Bestandsdaten.xml ist die originale GML-Datei
testOut.gml ist die neu erzeugte GML-Datei, in der die Sachen bereits ersetzt wurden
none|mini|pbar gibt an, wie man den Fortschritt visualisieren will, aber dazu unten mehr.

Ausgabe auf der Konsole ist dann:
Zeile 34567 von 34567
Anzahl der gesamten Zahl der Zeilen in der Datei: 34567
Anzahl der komplett ignorierten Zeilen: 15
Anzahl der nach CASE ignorierten Zeilen: 16054
Anzahl der beachteten Zeilen mit '</>': 6736
Anzahl der richtig geprüften Zeilen: 11762
Anzahl der Zeilen, in denen das des Umbennungsarrays durchlaufen wurde: 4370
Anzahl der Zeilen, in denen ersetzt wurde: 332

Die Indentation geht leider verloren, aber dafür gibt es 2 Wege:
1.  `sudo apt-get install tidy`
   `tidy -xml -i your-file.xml > output.xml`
2.  `xmllint --format input.xml --output output.xml`

Ich habe versucht, es so performant wie möglich zu machen, also z.B. das Array mit den Umbenennungsregeln möglichst wenig zu durchlaufen und konnte die Zahlen auch drücken, wie du hier siehst (getestet mit Bestandsdaten.xml, die 34567 Zeilen hat):
#nas2ogrgml.sh
Anzahl der Zeilen, in denen das des Umbennungsarrays durchlaufen wurde: 5028
Anzahl der Zeilen, in denen ersetzt wurde: 332
`time ./nas2ogrgml.sh Bestandsdaten.xml testOut.gml none|mini|pbar`
- mit progress (pbar): 5m48.026s | 3m31.564s | 3m24.759s
- mit mini. progress (mini): 0m56.309s | 0m55.479s
- ohne progress (none): 0m57.786s | 0m56.781s | 0m56.142s

#nas2ogrgml.sh v2 (weniger Umbennungsarraydurchläufe, CASE kostet wenig!, bringt aber auch nicht immer was...)
Anzahl der Zeilen, in denen das Umbennungsarrays durchlaufen wurde: 4370
Anzahl der Zeilen, in denen ersetzt wurde: 332
- mit mini. progress: 0m54.100s | 0m53.097s

Die Verringerung der Umbennungsarraydurchläufe hat also nicht allzu viel gebracht.

Zum Vergleich mal die speed.sh, die jede Zeile liest und sofort wieder schreibt:
- nur lesen und schreiben: 0m1.381s | 0m1.566s

Hier siehst du aber auch, dass es doch recht lange dauert, eine knapp 30 MiB große Datei (797790 Zeilen) braucht dann schon fast ne Stunde.
Du siehst auch den Einfluss der Progressbar auf die Performanz, die schon echt ordentlich ist. Einfach "Zeile X von Y" ist aber ok und verlangsamt nix, sollte man also bevorzugen.

**Comment by pkorduan** [comment]
Fertig gestellt in NAS-5-1
