### ISSUE TITLE
GUI-1 Namen der Schemata für Modell und GML + Aufruf

### ISSUE THREAD

**Issue by chseip** [pkorduan/xmi2db#17]
- [x] Benennung Schema mit Metamodell "schema_meta" oder "schema_uml"
- [x] Bennenung Schema mit GML Klassen "schema_classes" oder "schema_gml"
- [x] xmi2db ruft dbclasse auf, damit nach der Modellüberführung in die DB gleich die GML Klassen erzeugt werden

**Comment by pkorduan** [comment]
Hat sich alles mit anderen Tickets erledigt.
Metamodell heist jeweils aaa_uml oder xplan_uml.
Das Schema für die classes heist jetz
aaa_gml oder xplan_gml, weil es sich hier um Klassen konform zum GML handelt.
Zusätzlich gibt es jetzt noch eine Namensfestlegung für das flache Schema für ogr2ogr
aaa_ogr und xplan_ogr
