### ISSUE TITLE
GUI-2 Konvertierung asynchron machen

### ISSUE THREAD

**Issue by chseip** [pkorduan/xmi2db#18]
- [ ] index.php macht statt window.location einen Ajax/jQuery Aufruf
- [ ] DB extra Tabelle für Status Meldung (mit ID wegen Paralellität?)
- [ ] Oberfläche fragt Tabelle alle X Sekunden ab und gibt Statusmeldungen aus

**Comment by pkorduan** [comment]
Brauchen wir alles erstmal nicht mehr. Falls doch noch, kann das wieder aufgemacht werden.
