### ISSUE TITLE
NAS-4-1 Vervollständige flachmachen des Schemas

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#19]
- [x] Schript scheiben welches eine Umbenennungsliste erzeugt.
- [x] Berücksichtige Umbenennungsregeln beim Umbenennen.
- [x] Schema mit umbenannten Attributen schreiben.

**Comment by pkorduan** [comment]
Die Regeln zur Umbenennung sind in Funktion unifyShortNames($level) in Klasse FeatureType in classes/featuretype.php festgelegt.
1. Im 1. Durchlauf wird gezählt wie oft der letzte Teil des Names in einem FeatureType vorkommt.
2. Gibt es mehr als eine Doppelung (das Attribut mit sich selbst darf natürlich gleich sein)
2.1 werden an alle die Mehrfach vorkommen die Namen des jeweils vorherigen Namensteils vorangestellt, getrennt durch '_', es sei denn das Attribut hat nur einen Namen, bzw. 1 Verschachtelungstiefe.
2.2 und das Ganze wird mit einem erhöhtem Level von vorn wiederholt, maximal bis zu einem Level von 10.
Beispiel a, x_a, x_ b_a, x_c_d_a, x_e_d_a
nach 1. Level
a => a
a=> x_a
a => b_a
a => d_a
a => d_a
nach 2. Level
d_a => c_d_a
d_a => e_d_a
Am Ende beleiben:
a, x_a, b_a, c_d_a, e_d_a
Es wird also nur umbenannt was wirklich nötig ist.

**Comment by jef-n** [comment]
s. [unifyShortNames](https://github.com/pkorduan/xmi2db/blob/NAS-4-1/classes/featuretype.php#L83)

**Comment by pkorduan** [comment]
Fertig. Das vorläufige Schema kann abgerufen werden unter: http://gdi-service.de/xmi2db/db2ogr.php
