### ISSUE TITLE
NAS-8 Projekt aufräumen

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#30]
- [ ] XPlan2iQvoc in converter verschieben
- [x] pascoul in lib verschieben
- [x] pascoul wieder lauffähig machen
- [x] prüfen ob noch alles aus lib gebraucht wird.
- [x] README.md vervollständigen, z.B. Installationsanleitung für rename_nas.rb und verständliche Beschreibung.
- [x] README.md in Deutsch übersetzen und ein nur eine Zusammenfassung in Englisch.
- [x] class.xmi2db.rb umbenennen.
- [x] Neustart des Projektes prüfen mit den Migrationen aus sql, evtl. sql ergänzen.
- [x] xmi2db prüfen.
- [x] db2classes Schema in Datenbank einlesen und prüfen ob Fehler auftreten.
- [x] db2ogr Schema in Datenbank einlesen und prüfen ob Fehler auftreten.
- [x] Prüfen ob die Filter für Tabellen, Attribute und Beziehungen funktionieren.

**Comment by chseip** [comment]
- Fehler/Fehlendes in index.php:
  - "Das Schema wird entsprechend der gewählten Konfiguration in der Datenbank "kvwmapsp" angelegt." -> Datenbankname fehlte
  - "Abbrechen"-Button für xmi2db fehlt (xmi2db läuft ewig und kann nur schwer abgebrochen werden)
- Neues in index.php:
  - ruft jetzt direkt class.xmi2db.php auf
- xmi2db
  - da class.xmi2db.php direkt aufgerufen wird, entfällt xmi2db.php => class.xmi2db.php umbenannt in xmi2db.php und in "converter" verschoben
- alles von xmi2db über db2classes bis db2ogr auf dem BBSR Server nochmal durchgehend getestet => funktioniert (dabei fällt mir auf, dass es ganz schön wäre, wenn die Ergebnisse von db2classes und db2ogr als Bootstrap Overlay (schließbar) oder in einem neuen Tab kommen würden)

Ich wollte es gern pushen/commiten, da kommen Fehlrmeldungen, hab jetzt glaube ich einen merge gemacht, jetzt sagt er mir, das nichts mehr zu commiten ist. Seh da absolut nicht durch, sorry.
Auf dem BBSR Server (85.214.126.13) in /var/www/apps/xmi2db ist alles so, wie es sollte
Siehe: http://xplan-raumordnung.de/xmi2db/

**Comment by pkorduan** [comment]
Fertig
