### ISSUE TITLE
INSPIRE

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#32]
- [x] Modelle auch ohne Packages oder Subpackages lesen können
- [x] Package Konfiguration anpassen
  Wenn man kein Package angegeben hat in database_conf.php sollen alle Packages verwendet werden.
- [x] Konfiguration der Schemanamen

**Comment by chseip** [comment]
Ich merk grad, dass die Package Konfiguration in der db_conf bisher eh komplett ignoriert wurde, von daher muss man da auch nix angeben, das funktioniert also ;-)

Spaß beiseite, ich werde das jetzt mal nachholen...

Erste Erfolge s. https://github.com/pkorduan/xmi2db/commit/79ddc3de8651b29910909f6113186c4f7d07d80a

**Comment by chseip** [comment]
- Packages müssen in der database.conf nun anders angelegt werden, da das Komma bei einigen Packages stört. Sprich: `define('PACKAGES', "'" . implode("';'", $packages) . "'");` (hab ich beim Test mit AAA Modellen gemerkt; check ich nachher noch ein)
- INSPIRE läuft bei mir problemlos, soweit ich das überblicken kann, ohne, dass ich was weiteres geändert habe :-) (Zum Testen wären weitere Modelle schön, [hier](https://inspire-twg.jrc.ec.europa.eu/svn/inspire-model/branches/public/approved/latest/themes/) gibts zwar welche, aber die XMI Version ist zu alt und das anzupassen, ist denk ich sinnlos. Hab hier auch grad kein EA, sodass ich selbst umwanden könnte.)

Mach mit den Schemanamen weiter und checks am Ende ein...

**Comment by chseip** [comment]
Ich habe versucht, es so einfach wie möglich zu halten. Deshalb gibt man bei der index.php jetzt einen Parameter `conf` an, der z. Zt. die Werte `aaa`, `xplan` und `inspire` annehmen kann (z.B. `http://server/xmi2db/?conf=xplan`). Diese 3 Werte koresspondieren nämlich mit 3 Konfig-Dateien in conf/models (aaa.php, xplan.php und inspire.php). In diesen gibt man die Namen für Schema und die gewählten Pakete an.
Bitte darauf achten, dass in der database_conf.php die Packages raus sind!

Wählt man unter xmi2db ein Schema aus, ändern sich die anderen Auswahllisten automatisch mit. Das heißt, wählt man das Schema `aaa_uml` steht bei db2classes und db2ogr unter `UML-Schema` auch `aaa_uml`. Beim GML-Klassenschema wird dann automatisch `aaa_gml` und beim OGR-Schema `aaa_ogr` gewählt.

Für xmi2db hab ich es für AAA, XPlan und INSPIRE getestet. Für db2classes und db2ogr hab ich es noch nicht getestet.

Commit: https://github.com/pkorduan/xmi2db/commit/764418e4919c901d1f5a01a3d0c32f1fdcdf0a83
