### ISSUE TITLE
dev-4 Add 1:n accosications

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/xmi2db#6]
- [x] Tabellen, die nur 1:n Verknüpfungen haben um Spalte erweitern für den Eintrag des Fremdschlüssels.
- [x] Trennung im Tabellennamen von "2" auf "_zu_" ändern.
- [x] Primary Keys in n:m Tabellen setzen.
- [x] Überprüfen ob die Array Typen richtig gesetzt werden.

**Comment by RKraetschmer** [comment]
- Die Sequenznummer von Attributen wird in der Datenbank benötigt. Sie erlaubt die GML-Ordnung der Attribute nach Ordnung der Attribute im XSD. Ohne diese kommt es zu Validierungsfehlern.
- Die Definition von einzelnen Werten von Enumerationen wird in der Datenbank benötigt. So können Definitionen z.B. im SQL-QueryBuilder angezeigt werden.

**Comment by pkorduan** [comment]
Jetzt wird sortiert nach sequence number, die aus den tagedvalues ausgelesen werden. Beschreibungen der Werte von Enumerations stehen in den Tabellen enum_<EnumerationTypeName>
